-- Base de datos para el Sistema del Ministerio del Poder Popular para la Cultura

-- CREATE DATABASE 'ministerio_cultura.fdb' PAGE_SIZE 8192;

-- Tabla de usuarios del sistema
CREATE TABLE usuarios (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_completo VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    telefono VARCHAR(20),
    tipo_usuario VARCHAR(20) NOT NULL CHECK (tipo_usuario IN ('cultor', 'funcionario', 'publico')),
    password_hash VARCHAR(255) NOT NULL,
    fecha_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    activo SMALLINT DEFAULT 1 CHECK (activo IN (0, 1))
);

CREATE INDEX idx_usuarios_email ON usuarios (email);
CREATE INDEX idx_usuarios_tipo_usuario ON usuarios (tipo_usuario);

-- Tabla de cultores (practicantes culturales)
CREATE TABLE cultores (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombres_apellidos VARCHAR(255) NOT NULL,
    telefono VARCHAR(20) NOT NULL,
    cedula VARCHAR(20) NOT NULL UNIQUE,
    correo VARCHAR(255) NOT NULL UNIQUE,
    area_tematica VARCHAR(20) NOT NULL CHECK (area_tematica IN ('musica', 'danza', 'teatro', 'artesPlasticas', 'literatura', 'artesanias', 'cine', 'fotografia')),
    disciplina VARCHAR(100) NOT NULL,
    comuna VARCHAR(100) NOT NULL,
    municipio VARCHAR(100) NOT NULL,
    parroquia VARCHAR(100) NOT NULL,
    carnet_patria VARCHAR(50) NOT NULL,
    direccion VARCHAR(255) NOT NULL,
    lugar_nacimiento VARCHAR(100) NOT NULL,
    fecha_nacimiento DATE NOT NULL,
    edad INTEGER NOT NULL,
    trayectoria_anios INTEGER NOT NULL,
    organizacion VARCHAR(255) NOT NULL,
    fecha_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    activo SMALLINT DEFAULT 1 CHECK (activo IN (0, 1))
);

CREATE INDEX idx_cultores_cedula ON cultores (cedula);
CREATE INDEX idx_cultores_correo ON cultores (correo);
CREATE INDEX idx_cultores_area_tematica ON cultores (area_tematica);
CREATE INDEX idx_cultores_municipio ON cultores (municipio);

-- Tabla de eventos/actividades culturales
CREATE TABLE eventos (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    correo_usuario VARCHAR(255) NOT NULL,
    estado VARCHAR(50) NOT NULL,
    municipio VARCHAR(100) NOT NULL,
    parroquia VARCHAR(100) NOT NULL,
    organizacion VARCHAR(255) NOT NULL,
    tipo_organizacion VARCHAR(10) DEFAULT 'comuna' CHECK (tipo_organizacion IN ('comuna', 'circuito')),
    direccion VARCHAR(255) NOT NULL,
    ubicacion_exacta VARCHAR(255),
    consejo_comunal VARCHAR(255) NOT NULL,
    nombre_consejo VARCHAR(255),
    nombre_comuna VARCHAR(255) NOT NULL,

    -- Datos del vocero responsable
    vocero_nombre VARCHAR(255) NOT NULL,
    vocero_cedula VARCHAR(20) NOT NULL,
    vocero_telefono VARCHAR(20) NOT NULL,

    -- Datos del responsable por Misión Cultura
    responsable_nombre VARCHAR(255) NOT NULL,
    responsable_cedula VARCHAR(20) NOT NULL,
    responsable_telefono VARCHAR(20) NOT NULL,
    responsable_cargo VARCHAR(20) NOT NULL CHECK (responsable_cargo IN ('Animador', 'Coordinador', 'Facilitador', 'Tutor')),

    -- Descripción de la actividad
    tipo_actividad VARCHAR(100) NOT NULL,
    disciplina VARCHAR(50) NOT NULL,
    nombre_actividad VARCHAR(255) NOT NULL,
    objetivo VARCHAR(500) NOT NULL,

    -- Fecha y hora
    mes INTEGER NOT NULL,
    fecha DATE NOT NULL,
    hora TIME NOT NULL,
    duracion INTEGER NOT NULL, -- en horas

    -- Datos de participación
    ninos INTEGER DEFAULT 0,
    ninas INTEGER DEFAULT 0,
    jovenes_masculinos INTEGER DEFAULT 0,
    jovenes_femeninas INTEGER DEFAULT 0,
    adultos_masculinos INTEGER DEFAULT 0,
    adultos_femeninas INTEGER DEFAULT 0,

    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    activo SMALLINT DEFAULT 1 CHECK (activo IN (0, 1))
);

CREATE INDEX idx_eventos_fecha ON eventos (fecha);
CREATE INDEX idx_eventos_mes ON eventos (mes);
CREATE INDEX idx_eventos_disciplina ON eventos (disciplina);
CREATE INDEX idx_eventos_estado ON eventos (estado);
CREATE INDEX idx_eventos_municipio ON eventos (municipio);

-- Tabla de publicaciones del foro
CREATE TABLE foro_publicaciones (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INTEGER,
    titulo VARCHAR(255) NOT NULL,
    categoria VARCHAR(20) NOT NULL CHECK (categoria IN ('danza', 'musica', 'artesPlasticas', 'poesia', 'teatro', 'cine', 'fotografia', 'artesanias')),
    descripcion BLOB SUB_TYPE TEXT NOT NULL,
    archivo_url VARCHAR(500), -- URL del archivo multimedia
    tipo_archivo VARCHAR(10) CHECK (tipo_archivo IN ('imagen', 'video', 'audio')),
    fecha_publicacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    activo SMALLINT DEFAULT 1 CHECK (activo IN (0, 1)),
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE SET NULL
);

CREATE INDEX idx_foro_publicaciones_categoria ON foro_publicaciones (categoria);
CREATE INDEX idx_foro_publicaciones_fecha ON foro_publicaciones (fecha_publicacion);

-- Tabla de comentarios en el foro
CREATE TABLE foro_comentarios (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    publicacion_id INTEGER NOT NULL,
    usuario_id INTEGER,
    comentario BLOB SUB_TYPE TEXT NOT NULL,
    fecha_comentario TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    activo SMALLINT DEFAULT 1 CHECK (activo IN (0, 1)),
    FOREIGN KEY (publicacion_id) REFERENCES foro_publicaciones(id) ON DELETE CASCADE,
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE SET NULL
);

CREATE INDEX idx_foro_comentarios_publicacion ON foro_comentarios (publicacion_id);
CREATE INDEX idx_foro_comentarios_fecha ON foro_comentarios (fecha_comentario);


-- Insertar datos de ejemplo para pruebas

-- Usuario administrador de ejemplo
INSERT INTO usuarios (nombre_completo, email, telefono, tipo_usuario, password_hash) VALUES
('Administrador Sistema', 'admin@mincultura.gob.ve', '02121234567', 'funcionario', '$2b$10$example.hash.here');

-- Cultor de ejemplo
INSERT INTO cultores (nombres_apellidos, telefono, cedula, correo, area_tematica, disciplina, comuna, municipio, parroquia, carnet_patria, direccion, lugar_nacimiento, fecha_nacimiento, edad, trayectoria_anios, organizacion) VALUES
('María González', '04141234567', 'V-12345678', 'maria.gonzalez@email.com', 'musica', 'Cuatro venezolano', 'Comuna 1', 'Libertador', 'Catedral', '123456789012', 'Av. Principal 123', 'Caracas', '1985-03-15', 39, 15, 'Fundación Música Venezolana');

-- Evento de ejemplo
INSERT INTO eventos (correo_usuario, estado, municipio, parroquia, organizacion, direccion, consejo_comunal, nombre_comuna, vocero_nombre, vocero_cedula, vocero_telefono, responsable_nombre, responsable_cedula, responsable_telefono, responsable_cargo, tipo_actividad, disciplina, nombre_actividad, objetivo, mes, fecha, hora, duracion, ninos, ninas, jovenes_masculinos, jovenes_femeninas, adultos_masculinos, adultos_femeninas) VALUES
('admin@mincultura.gob.ve', 'Distrito Capital', 'Libertador', 'Catedral', 'Fundación Música Venezolana', 'Teatro Nacional', 'Consejo Comunal Catedral', 'Comuna Catedral', 'Juan Pérez', 'V-87654321', '04149876543', 'Ana López', 'V-11223344', '04145566778', 'Coordinador', 'Presentación artística', 'música', 'Concierto de Música Tradicional', 'PROMOCIÓN DE LA PARTICIPACIÓN POPULAR', 1, '2024-01-15', '19:00:00', 2, 10, 15, 8, 12, 25, 30);

-- Publicación de foro de ejemplo
INSERT INTO foro_publicaciones (titulo, categoria, descripcion) VALUES
('Compartiendo mi última composición', 'musica', 'He estado trabajando en una nueva pieza inspirada en la música tradicional venezolana. ¡Me gustaría compartirla con la comunidad!');

-- Tabla de noticias
CREATE TABLE noticias (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(255) NOT NULL,
    contenido BLOB SUB_TYPE TEXT NOT NULL,
    imagen_url VARCHAR(500),
    fecha_publicacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    autor_id INTEGER,
    activo SMALLINT DEFAULT 1 CHECK (activo IN (0, 1)),
    FOREIGN KEY (autor_id) REFERENCES usuarios(id) ON DELETE SET NULL
);

CREATE INDEX idx_noticias_fecha ON noticias (fecha_publicacion);
CREATE INDEX idx_noticias_activo ON noticias (activo);

-- Insertar noticias de ejemplo
INSERT INTO noticias (titulo, contenido) VALUES
('Gran concierto nacional celebra la cultura venezolana', 'Eventos culturales se realizan en todo el país promoviendo la identidad nacional...'),
('Nueva exposición en la Galería de Arte Nacional', 'Artistas venezolanos presentan sus obras más recientes al público caraqueño...'),
('Feria del Libro 2026 anuncia invitados especiales', 'Escritores nacionales e internacionales participarán en el evento literario...');